name: namer_app
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0

  english_words: ^4.0.0
  provider: ^6.1.2
  flutter_colorpicker: ^1.0.3
  go_router: ^6.0.0  
  equatable: ^2.0.5
  fpdart: ^1.1.1
  supabase_flutter: ^2.8.3
  get_it: ^8.0.3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
