name: namer_app
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  flutter_colorpicker: ^1.0.3
  go_router: ^6.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
